jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: buenosdev
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Step to change the background color of the SVG
      - name: Change SVG Background Color
        run: |
          sed -i 's/<svg/<svg style="background-color:#FFFFFF"/' dist/github-contribution-grid-snake.svg
          
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
