jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: buenosdev
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step to change the background color of the SVG using Python
      - name: Change SVG Background Color
        run: |
          python -c "
import xml.etree.ElementTree as ET
tree = ET.parse('dist/github-contribution-grid-snake.svg')
root = tree.getroot()
root.set('style', 'background-color:#FFFFFF')
tree.write('dist/github-contribution-grid-snake.svg')
          "

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
